---
endpoints:
  AuthURL:  https://token.company.com/ccess_token
  TokenURL: https://auth.company.com/oauth2/tokeninfo

allowedUsers:
    - username: employee1
      fullname: First Employee
      role: employees
      group: root
    - username: employee2
      fullname: Second Employee
      role: employees
      group: root
    - username: emergencyuser1
      fullname: First EmergencyUser
      role: employees
      group: emergency

security:
  certFile : ./company.crt
  keyFile : ./company.key

documentation:
  ltmdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/local%20trafficmanager/index.html
  gtmdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/global%20trafficmanager/index.html
  ltmpooldocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/local%20trafficmanager/pools.html
  ltmpoolmemberdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/local%20trafficmanager/poolmembers.html
  ltmvirtualdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/local%20trafficmanager/virtual-servers.html
  ltmdatagroupdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/local%20trafficmanager/datagroups.html
  ltmaddresslistdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/local%20trafficmanager/addresslist.html
  gtmwideipdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/global%20trafficmanager/wideips.html
  gtmpooldocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/global%20trafficmanager/pools.html
  gtmpoolmemberdocumentationuri : https://techmonkeys.readthedocs.org/en/latest/baboon-proxy/global%20trafficmanager/poolmembers.html

ltmdevicenames:
  dc-east-ltm01 : 123.123.123.123
  dc-east-ltm02 : 123.123.123.124
  dc-west-ltm01 : 177.177.177.100
  dc-west-ltm02 : 177.177.177.101

externalgtmlisteners:
  dc-east-gtm01: 11.11.11.11:53
  dc-east-gtm02: 11.11.11.12:53
  dc-west-gtm01: 13.13.13.13:53
  dc-west-gtm02: 13.13.13.14:53

internalgtmlisteners:
  dc-east-itm01: 10.0.0.1:53
  dc-east-itm02: 10.0.0.2:53
  dc-west-itm01: 192.168.0.1:53
  dc-west-itm02: 192.168.0.2:53

backend:
  f5user: admin
  f5password: password

partition:
  gtm: Common 
  ltm: Common

gtmmgmtip:
  dc-east-gtm01: 11.11.11.1
  dc-east-gtm02: 11.11.11.2
  dc-west-gtm01: 13.13.13.1
  dc-west-gtm02: 13.13.13.2

ltmmgmtip:
  dc-east-itm01: 10.0.0.4
  dc-east-itm02: 10.0.0.5

itmmgmtip:
  dc-east-ltm01 : 123.123.123.123
  dc-east-ltm02 : 123.123.123.124
  dc-west-ltm01 : 177.177.177.100
  dc-west-ltm02 : 177.177.177.101

snmp:
  community: Public
  version: 2c
  timeout: 5
  port: 161
  oids:
    common:
      version: 1.3.6.1.4.1.3375.2.1.4.2.0
      hotfix:  1.3.6.1.4.1.3375.2.1.4.4.0
      devicestatus: 1.3.6.1.4.1.3375.2.1.14.3.1.0
    gtm:
      pool: 1.3.6.1.4.1.3375.2.3.6.3.2.1.1
      poolstatus: 1.3.6.1.4.1.3375.2.3.6.3.2.1.5
      server: 1.3.6.1.4.1.3375.2.3.9.1.2.1.1
      serverstatus: 1.3.6.1.4.1.3375.2.3.9.3.2.1.2
      wideip: 1.3.6.1.4.1.3375.2.3.12.1.2.1.1
      wideipstatus: 1.3.6.1.4.1.3375.2.3.12.3.2.1.5
    ltm:
